apiVersion: apps/v1
kind: Deployment
metadata:
  name: postfix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postfix
  template:
    metadata:
      labels:
        app: postfix
    spec:
      containers:
      - name: postfix
        image: catatnight/postfix:latest
        env:
        - name: maildomain
          value: mail.example.co.jp
        - name: smtp_user
          value: usere:password
#        image: mailu/postfix:latest
#        image: postfixadmin:latest
#        env:
#        - name: POSTFIXADMIN_DB_TYPE
#          value: mysqli
#        - name: POSTFIXADMIN_DB_HOST
#          value: whatever
#        - name: POSTFIXADMIN_DB_USER
#          value: user
#        - name: POSTFIXADMIN_DB_PASSWORD
#          value: topsecret
#        - name: POSTFIXADMIN_DB_NAME
#          value: postfixadmin
        ports:
        - name: smtp
          containerPort: 25
        - name: smtp-auth
          containerPort: 587
        command:
        - sh
        - "-c"
        - |
          echo "[mail.example.co.jp]     smtp-user-name:smtp-user-passwd" > /etc/postfix/smtp-auth-passwd && \
          sed -i "s/relayhost = /relayhost = [mail.example.co.jp]/" /etc/postfix/main.cf && \
          sed -i "s|mynetworks \= 127\.0\.0\.0\/8 \[\:\:ffff\:127\.0\.0\.0\]\/104 \[\:\:1\]\/128|mynetworks \= 127\.0\.0\.0\/8 \[\:\:ffff\:127\.0\.0\.0]\/104 \[\:\:1\]\/128 0\.0\.0\.0\/0|" /etc/postfix/main.cf && \
          echo "smtp_sasl_auth_enable  = yes" >> /etc/postfix/main.cf && \
          echo "smtp_sasl_password_maps = hash:/etc/postfix/smtp-auth-passwd" >> /etc/postfix/main.cf && \
          echo "smtp_sasl_security_options = noanonymous" >> /etc/postfix/main.cf && \
          echo "smtp_sasl_mechanism_filter =  plain, login" >> /etc/postfix/main.cf && \
          echo "transport_maps = hash:/etc/postfix/transport" >> /etc/postfix/main.cf && \
          echo "example.co.jp                 smtp:" >> /etc/postfix/transport && \
          echo "localhost                 local:" >> /etc/postfix/transport && \
          echo "localhost.localdomain     local:" >> /etc/postfix/transport && \
          echo "*                         discard: "discard received email"" >> /etc/postfix/transport && \
          postmap /etc/postfix/transport && \
          echo $? && \
          sed -i "s/postconf -e smtpd_recipient_restrictions=permit_sasl_authenticated,reject_unauth_destination/#postconf -e smtpd_recipient_restrictions=permit_sasl_authenticated,reject_unauth_destination/" /opt/install.sh && \
          /bin/sh -c /opt/install.sh;/usr/bin/supervisord -c /etc/supervisor/supervisord.conf
#          sed -i "s/mydestination = dd40882ba0ea, localhost.localdomain, , localhost/mydestination = /" /etc/postfix/main.cf && \
#          sed -i "s|mynetworks \= 127\.0\.0\.0\/8 \[\:\:ffff\:127\.0\.0\.0\]\/104 \[\:\:1\]\/128|mynetworks \= 127\.0\.0\.0\/8 \[\:\:ffff\:127\.0\.0\.0]\/104 \[\:\:1\]\/128 10\.1\.1\.0\/24|" /etc/postfix/main.cf && \
