apiVersion: v1
kind: Service
metadata:
  name: postfix-sv
  labels:
    app: postfix
spec:
  selector:
    app: postfix
  ports:
  - name: smtp
    port: 25
    targetPort: 25
    protocol: TCP
  - name: smtp-auth
    port: 587
    targetPort: 587
    protocol: TCP