{{- if default "" .Values.externalUrl }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "gitlab-ce.fullname" . }}
  labels:
    app: {{ template "gitlab-ce.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "gitlab-ce.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "gitlab-ce.fullname" . }}
    spec:
      containers:
      - name: {{ template "gitlab-ce.fullname" . }}
        image: {{ .Values.image }}
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        env:
        ## General GitLab Configs
        ##
        # This is a free-form env var that GitLab Omnibus uses to configure
        # everything. We're passing this in from a configmap and pulling some
        # of the values from the env vars defined below. This is done to
        # avoid leaving secrets visible in kubectl.
        - name: GITLAB_OMNIBUS_CONFIG
          valueFrom:
            configMapKeyRef:
              name: {{ template "gitlab-ce.fullname" . }}
              key: gitlab_omnibus_config
        - name: GITLAB_ROOT_PASSWORD
        {{- if default "" .Values.gitlabRootPassword }}
          valueFrom:
            secretKeyRef:
              name: {{ template "gitlab-ce.fullname" . }}
              key: gitlab-root-password
        {{ end }}
        - name: EXTERNAL_URL
          value: {{ default "" .Values.externalUrl | quote }}
        command:
        - sh
        - "-c"
        - |
          mkdir -p /opt/gitlab/embedded/etc && \
          touch /opt/gitlab/embedded/etc/90-omnibus-gitlab-kernel.shmmax.conf && \
          ln -s /opt/gitlab/embedded/etc/90-omnibus-gitlab-kernel.shmmax.conf /opt/gitlab/embedded/etc/90-omnibus-gitlab-kernel.sem.conf >/dev/null 2>&1 && \
          rm -rf /opt/gitlab/embedded/etc/90-omnibus-gitlab-kernel.shmmax.conf && \
          /assets/wrapper
#          tail -f /dev/null
        ports:
        - name: ssh
          containerPort: 22
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        livenessProbe:
          httpGet:
            path: /help
            port: {{ .Values.livenessPort }}
          # This pod takes a very long time to start up. Be cautious when
          # lowering this value to avoid Pod death during startup.
          initialDelaySeconds: 200
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: /help
            port: {{ .Values.readinessPort }}
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        volumeMounts:
        - name: gitlab-pvc-etc
          mountPath: /etc
        - name: gitlab-pvc-log
          mountPath: /var/log
        - name: gitlab-pvc-opt
          mountPath: /var/opt
        resources:
{{ toYaml .Values.resources | indent 10 }}
      volumes:
      - name: gitlab-pvc-etc
      {{- if .Values.persistence.gitlabEtc.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "gitlab-ce.fullname" . }}-pvc-etc
      {{- else }}
        emptyDir: {}
      {{- end }}
      - name: gitlab-pvc-log
      {{- if .Values.persistence.gitlabLog.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "gitlab-ce.fullname" . }}-pvc-log
      {{- else }}
        emptyDir: {}
      {{- end }}
      - name: gitlab-pvc-opt
      {{- if .Values.persistence.gitlabOpt.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "gitlab-ce.fullname" . }}-pvc-opt
      {{- else }}
        emptyDir: {}
      {{- end }}
{{ else }}
{{ end }}
