{{- if .Values.persistence.gitlabEtc.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "gitlab-ce.fullname" . }}-etc
  annotations:
  {{- if .Values.persistence.gitlabEtc.storageClass }}
    storageClassName: {{ .Values.persistence.gitlabEtc.storageClass | quote }}
  {{- else }}
    storageClassName: manual
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.gitlabEtc.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.gitlabEtc.size | quote }}
{{- end }}
