{{- if (.Values.persistence.gitlabEtc.enabled) and .Values.persistence.gitlabEtc.storageClass eq "manual" }}
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ template "gitlab-ce.fullname" . }}-pv-etc
spec:
  capacity:
    storage: {{ .Values.persistence.gitlabEtc.size | quote }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /etc
{{- end }}
