{{- if .Values.persistence.gitlabEtc.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "gitlab-ce.fullname" . }}-etc
  annotations:
  {{- if .Values.persistence.gitlabEtc.storageClass ne "pv-etc" }}
  {{- if .Values.persistence.gitlabEtc.storageClass }}
    volume.beta.kubernetes.io/storage-class: {{ .Values.persistence.gitlabEtc.storageClass | quote }}
  {{- else }}
    volume.alpha.kubernetes.io/storage-class: default
  {{- end }}
  {{- end }}
spec:
  storageClassName: pv-etc
  accessModes:
  - {{ .Values.persistence.gitlabEtc.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.gitlabEtc.size | quote }}
{{- end }}
