{{- if (.Values.persistence.gitlabLog.enabled) and .Values.persistence.gitlabLog.storageClass eq "pv-log" }}
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ template "gitlab-ce.fullname" . }}-pv-log
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.persistence.gitlabLog.size | quote }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: pv-log
  hostPath:
    path: /data
{{- end }}
