{{- if (.Values.persistence.gitlabEtc.enabled) and .Values.persistence.gitlabEtc.storageClass eq "local-storage" }}
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ template "gitlab-ce.fullname" . }}-pv-etc
spec:
  storageClassName: {{ .Values.persistence.gitlabEtc.storageClass }}
  capacity:
    storage: {{ .Values.persistence.gitlabEtc.size | quote }}
  accessModes:
  - ReadWriteOnce
  local:
    path: /etc/gitlab
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker
{{- end }}
