{{- if .Values.persistence.gitlabEtc.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "gitlab-ce.fullname" . }}-pvc-etc
spec:
  {{- if .Values.persistence.gitlabEtc.storageClass }}
  storageClassName: {{ .Values.persistence.gitlabEtc.storageClass | quote }}
  {{- else }}
  storageClassName: local-storage
  {{- end }}
  accessModes:
  - {{ .Values.persistence.gitlabEtc.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.gitlabEtc.size | quote }}
{{- end }}
