{{- if default "" .Values.externalUrl }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "gitlab-ce.fullname" . }}
  labels:
    app: {{ template "gitlab-ce.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "gitlab-ce.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "gitlab-ce.fullname" . }}
    spec:
      containers:
      - name: {{ template "gitlab-ce.fullname" . }}
        image: {{ .Values.image }}
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        env:
        ## General GitLab Configs
        ##
        # This is a free-form env var that GitLab Omnibus uses to configure
        # everything. We're passing this in from a configmap and pulling some
        # of the values from the env vars defined below. This is done to
        # avoid leaving secrets visible in kubectl.
        - name: GITLAB_OMNIBUS_CONFIG
          valueFrom:
            configMapKeyRef:
              name: {{ template "gitlab-ce.fullname" . }}
              key: gitlab_omnibus_config
        - name: GITLAB_ROOT_PASSWORD
        {{- if default "" .Values.gitlabRootPassword }}
          valueFrom:
            secretKeyRef:
              name: {{ template "gitlab-ce.fullname" . }}
              key: gitlab-root-password
        {{ end }}
        - name: EXTERNAL_URL
          value: {{ default "" .Values.externalUrl | quote }}
        - name: TZ
          value: {{ .Values.env.timezone }}
        - name: LANG
          value: {{ .Values.env.lang }}
        - name: LANGUAGE
          value: {{ .Values.env.language }}
        - name: LC_ALL
          value: {{ .Values.env.lc_all }}
        command:
        - sh
        - "-c"
        - |
          mkdir -p /opt/gitlab/embedded/etc && \
          touch /opt/gitlab/embedded/etc/90-omnibus-gitlab-kernel.shmmax.conf && \
          ln -s /opt/gitlab/embedded/etc/90-omnibus-gitlab-kernel.shmmax.conf /opt/gitlab/embedded/etc/90-omnibus-gitlab-kernel.sem.conf >/dev/null 2>&1 && \
          ln -s /opt/gitlab/embedded/etc/90-omnibus-gitlab-kernel.shmmax.conf /opt/gitlab/embedded/etc/90-omnibus-gitlab-kernel.shmall.conf >/dev/null 2>&1 && \
          ln -s /opt/gitlab/embedded/etc/90-omnibus-gitlab-kernel.shmmax.conf /opt/gitlab/embedded/etc/90-omnibus-gitlab-net.core.somaxconn.conf >/dev/null 2>&1 && \
          rm -rf /opt/gitlab/embedded/etc/90-omnibus-gitlab-kernel.shmmax.conf && \
          sed -i "s/\# registry_external_url 'https:\/\/registry.example.com'/registry_external_url 'https:\/\/registry.example.com:4567'/" /opt/gitlab/etc/gitlab.rb.template && \
          sed -i "s@\#.nginx\['ssl_certificate'\].=.\"/etc/gitlab/ssl/\#{node\['fqdn'\]}\.crt\"@nginx\['ssl_certificate'\] = \"/etc/gitlab/ssl/registry\.example\.com\.crt\"@" /opt/gitlab/etc/gitlab.rb.template && \
          sed -i "s@\# nginx\['ssl_certificate_key'\] = \"/etc/gitlab/ssl/\#{node\['fqdn'\]}\.key\"@nginx\['ssl_certificate_key'\] = \"/etc/gitlab/ssl/registry\.example\.com\.key\"@" /opt/gitlab/etc/gitlab.rb.template && \
          sed -i "s/\# gitlab_rails\['registry_enabled'\] = true/gitlab_rails\['registry_enabled'\] = true" /opt/gitlab/etc/gitlab.rb.template && \
          mkdir -p /etc/gitlab/ssl && \
          ln -s /etc/ssl/regist-crt/registry.example.com.crt /etc/gitlab/ssl/registry.example.com.crt && \
          ln -s /etc/ssl/regist-key/registry.example.com.key /etc/gitlab/ssl/registry.example.com.key && \
          apt-get update && \
          apt-get -y install task-japanese locales-all && \
          /assets/wrapper
#          openssl req -newkey rsa:4096 -nodes -sha256 -keyout /etc/gitlab/ssl/registry.example.com.key -x509 -days 3650 \
#            -out /etc/gitlab/ssl/registry.example.com.crt \
#            -subj "/C=JP/ST=Hyogo/L=Kobe-shi/O=DIGITAL ALLIANCE HOLDINGS CO.,LTD/OU=Solution Division/CN=registry.example.com/emailAddress=hatakeyama@d-a.co.jp" && \
#          tail -f /dev/null
        ports:
        - name: ssh
          containerPort: 22
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        - name: regist
          containerPort: 4567
        livenessProbe:
          httpGet:
            path: /help
            port: {{ .Values.healthCheck.liveness.lPort }}
            scheme: {{ .Values.healthCheck.liveness.lScheme }}
          # This pod takes a very long time to start up. Be cautious when
          # lowering this value to avoid Pod death during startup.
          initialDelaySeconds: {{ .Values.healthCheck.liveness.lInitDelaySec }}
          timeoutSeconds: {{ .Values.healthCheck.liveness.lTimeoutSec }}
          periodSeconds: {{ .Values.healthCheck.liveness.lPeriodSec }}
          successThreshold: {{ .Values.healthCheck.liveness.lSuccessCnt }}
          failureThreshold: {{ .Values.healthCheck.liveness.lFailCnt }}
        readinessProbe:
          httpGet:
            path: /help
            port: {{ .Values.healthCheck.readiness.rPort }}
            scheme: {{ .Values.healthCheck.readiness.rScheme }}
          initialDelaySeconds: {{ .Values.healthCheck.readiness.rInitDelaySec }}
          timeoutSeconds: {{ .Values.healthCheck.readiness.rTimeoutSec }}
          periodSeconds: {{ .Values.healthCheck.readiness.rPeriodSec }}
          successThreshold: {{ .Values.healthCheck.readiness.rSuccessCnt }}
          failureThreshold: {{ .Values.healthCheck.readiness.rFailCnt }}
        volumeMounts:
        - name: gitlab-pvc-etc
          mountPath: /etc
        - name: gitlab-pvc-log
          mountPath: /var/log
        - name: gitlab-pvc-opt
          mountPath: /var/opt
        - name: regist-crt
          mountPath: /etc/ssl/regist-crt
        - name: regist-key
          mountPath: /etc/ssl/regist-key
        - name: gitlab-crt
          mountPath: /etc/ssl/gitlab-crt
        - name: gitlab-key
          mountPath: /etc/ssl/gitlab-key
        resources:
{{ toYaml .Values.resources | indent 10 }}
      volumes:
      - name: gitlab-pvc-etc
      {{- if .Values.persistence.gitlabEtc.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "gitlab-ce.fullname" . }}-pvc-etc
      {{- else }}
        emptyDir: {}
      {{- end }}
      - name: gitlab-pvc-log
      {{- if .Values.persistence.gitlabLog.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "gitlab-ce.fullname" . }}-pvc-log
      {{- else }}
        emptyDir: {}
      {{- end }}
      - name: gitlab-pvc-opt
      {{- if .Values.persistence.gitlabOpt.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "gitlab-ce.fullname" . }}-pvc-opt
      {{- else }}
        emptyDir: {}
      {{- end }}
      - name: regist-crt
        secret:
          secretName: secret-ssl-regist
          items:
          - key: tls.crt
            path: registry.example.com.crt
      - name: regist-key
        secret:
          secretName: secret-ssl-regist
          items:
          - key: tls.key
            path: registry.example.com.key
      - name: gitlab-crt
        secret:
          secretName: secret-ssl-gitlab
          items:
          - key: tls.crt
            path: gitlab.cluster.local.crt
      - name: gitlab-key
        secret:
          secretName: secret-ssl-gitlab
          items:
          - key: tls.key
            path: gitlab.cluster.local.key
{{ else }}
{{ end }}
