{{- if .Values.persistence.gitlabVar.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "gitlab-ce.fullname" . }}-var
  annotations:
  {{- if (.Values.persistence.gitlabVar.storageClass) and (ne .Values.persistence.gitlabVar.storageClass "pv-var") }}
  {{- if .Values.persistence.gitlabVar.storageClass }}
    volume.beta.kubernetes.io/storage-class: {{ .Values.persistence.gitlabVar.storageClass | quote }}
  {{- else }}
    volume.alpha.kubernetes.io/storage-class: default
  {{- end }}
  {{- end }}
spec:
  storageClassName: pv-var
  accessModes:
  - {{ .Values.persistence.gitlabVar.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.gitlabVar.size | quote }}
{{- end }}
