apiVersion: v1
name: apache-php
version: {{ .Values.image.tag }}
appVersion: 2.4.0
description: Chart for apache.
keywords:
  - apache
home: https://httpd.apache.org/
icon: https://www.apache.org/images/SupportApache-small.png
sources:
  - https://github.com/apache/httpd
maintainers:
- name: tadanobu.hatakeyama
  email: hatakeyama@d-a.co.jp
engine: gotpl
