piVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nuxt
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nuxt
    spec:
      containers:
      - name: nuxt
        image: php-gke-nuxt:latest
        env:
        - name: NODE_ENV
          value: "production"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: disk
          mountPath: "/mnt/src"
        command:
        - sh
        - "-c"
        - |
          ln -s /mnt/src/example1.co.jp /home/example1.co.jp && \
          ln -s /mnt/src/example2.co.jp /home/example2.co.jp && \
          ln -s /mnt/src/laravel-project /home/laravel-project && \
          cd /home/laravel-project/nuxtapp/ && \
          npm run build && \
          npm run start >> /var/log/nuxt.log 2>&1
#          echo "10.7.252.3 laravel-project.hatake.test" >> /etc/hosts
      volumes:
      - name: disk
        persistentVolumeClaim:
          claimName: php-src-sample-pvc
