kind: PersistentVolume
apiVersion: v1
metadata:
  name: nuxt-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /var/log/nuxt
