apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache-php
  template:
    metadata:
      labels:
        app: apache-php
    spec:
      containers:
      - name: apache-php
        image: {{ template "apachePhp.image" . }}
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
#        env:
#        - name: LC_CTYPE
#          value: ja_JP.utf8
        command:
        - sh
        - "-c"
        - |
          ln -s /var/www/html/php-example/example1.co.jp /home/example1.co.jp && \
          ln -s /var/www/html/php-example/example2.co.jp /home/example2.co.jp && \
          ln -s /var/www/html/php-example/laravel-project /home/laravel-project && \
          ln -s /var/www/html/php-example/nuxtapp /home/nuxtapp && \
          supervisord -c /etc/supervisord.conf
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        volumeMounts:
        - name: disk
          mountPath: "/home/nuxtapp/log"
        securityContext:
          privileged: true
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 10080
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.livenessProbe.successThreshold }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 10080
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.readinessProbe.successThreshold }}
          failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
      imagePullSecrets:
      - name: secret-registry
      volumes:
      - name: disk
        persistentVolumeClaim:
          claimName: apache-php-pvc
