kind: PersistentVolume
apiVersion: v1
metadata:
  name: apache-php-pv
spec:
  serviceAccountName: apache-php
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  hostPath:
    path: /var/log/httpd
