kind: PersistentVolume
apiVersion: v1
metadata:
  name: apache-php-pv
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /var/log/httpd
