kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: apache-php-pvc
spec:
  serviceAccountName: apache-php
  accessModes:
  - ReadWriteOnce
  storageClassName: hostpath
  resources:
    requests:
      storage: 1Gi
