# Source: gitlab-runner/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: "Role"
metadata:
  name: apache-php
  labels:
    app: apache-php
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
# Source: gitlab-runner/templates/role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: "RoleBinding"
metadata:
  name: apache-php
  labels:
    app: apache-php
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: "Role"
  name: apache-php
subjects:
- kind: ServiceAccount
  name: apache-php
  namespace: "default"
