apiVersion: v1
name: postfix
version: 1.0.0
appVersion: 1.0.0
description: Chart for postfix.
keywords:
  - postfix
  - mail
home: http://www.postfix.org/
icon: http://www.postfix.org/mysza.gif
sources:
  - http://www.postfix.org/download.html
maintainers:
- name: tadanobu.hatakeyama
  email: hatakeyama@d-a.co.jp
engine: gotpl
