apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: php-fpm
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: php-fpm
    spec:
      containers:
      - name: php-fpm
        image: php-gke-php:latest
#        env:
#        - name: LC_CTYPE
#          value: ja_JP.utf8
        command:
          - sh
          - "-c"
          - |
            ln -s /mnt/src/example1.co.jp /home/example1.co.jp && \
            ln -s /mnt/src/example2.co.jp /home/example2.co.jp && \
            ln -s /mnt/src/laravel-project /home/laravel-project && \
            rm -rf /mnt/src/laravel-project/www/public/vue/js/entry-client.js && \
            rm -rf /mnt/src/laravel-project/www/public/vue/css/app.css && \
            ln -s /mnt/src/laravel-project/laravelapp/public/js/vue/entry-client.js /mnt/src/laravel-project/www/public/vue/js/entry-client.js && \
            ln -s /mnt/src/laravel-project/laravelapp/public/css/app.css /mnt/src/laravel-project/www/public/vue/css/app.css && \
            /usr/local/bin/dns-regist.sh && \
            /etc/init.d/blackfire-agent restart && \
            php-fpm
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: disk
          mountPath: "/mnt/src"
        securityContext:
          privileged: true
      volumes:
      - name: disk
        persistentVolumeClaim:
          claimName: php-src-sample-pvc
