apiVersion: v1
kind: Service
metadata:
  name: dns-sv
  labels:
    app: dns
spec:
  selector:
    app: dns
  ports:
  - name: dns
    targetPort: 53
    port: 53
    protocol: UDP
  - name: dns-tcp
    targetPort: 53
    port: 53
    protocol: TCP
  - name: metrics
    targetPort: 953
    port: 953
    protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dns
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dns
    spec:
      containers:
      - name: dns
        image: dns:latest
        ports:
        - name: dns
          containerPort: 53
          protocol: UDP
        - name: dns-tcp
          containerPort: 53
          protocol: TCP
        - name: metrics
          containerPort: 953
          protocol: TCP
#        command:
#        - sh
#        - "-c"
#        - |
#          /bin/sh -c /opt/install.sh;/usr/bin/supervisord -c /etc/supervisor/supervisord.conf
