apiVersion: v1
kind: Service
metadata:
  name: dns-sv
  labels:
    app: dns
spec:
  selector:
    app: dns
  ports:
  - name: dns
    targetPort: 53
    port: 53
    protocol: UDP
  - name: dns-tcp
    targetPort: 53
    port: 53
    protocol: TCP
  - name: metrics
    targetPort: 953
    port: 953
    protocol: TCP
