apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-03-25T14:50:10Z"
  generation: 1
  labels:
    cattle.io/creator: norman
  name: docker-registry
  namespace: p-5crxt-pipeline
  resourceVersion: "1220834"
  selfLink: /apis/apps/v1/namespaces/p-5crxt-pipeline/deployments/docker-registry
  uid: 08d165ba-a1e4-4a4d-9e75-f89c28b9bfe0
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: docker-registry
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: docker-registry
      name: docker-registry
    spec:
      containers:
      - env:
        - name: REGISTRY_HTTP_ADDR
          value: 0.0.0.0:443
        - name: REGISTRY_HTTP_TLS_CERTIFICATE
          value: /opt/crt/client.cert
        - name: REGISTRY_HTTP_TLS_KEY
          value: /opt/crt/client.key
        - name: REGISTRY_AUTH
          value: htpasswd
        - name: REGISTRY_AUTH_HTPASSWD_REALM
          value: Registry Realm
        - name: REGISTRY_AUTH_HTPASSWD_PATH
          value: /opt/auth/registry-token
        image: registry:2
        imagePullPolicy: Always
        name: docker-registry
        ports:
        - containerPort: 443
          name: docker-registry
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 200M
          requests:
            cpu: 100m
            memory: 100M
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/crt/
          name: crt
          readOnly: true
        - mountPath: /opt/auth/
          name: auth
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: crt
        secret:
          defaultMode: 420
          secretName: registry-crt
      - name: auth
        secret:
          defaultMode: 420
          items:
          - key: registry-token
            path: registry-token
          secretName: pipeline-secret
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-03-25T14:50:22Z"
    lastUpdateTime: "2020-03-25T14:50:22Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-03-25T14:50:10Z"
    lastUpdateTime: "2020-03-25T14:50:22Z"
    message: ReplicaSet "docker-registry-68d44b9d47" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
