apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-03-25T14:50:10Z"
  generation: 1
  labels:
    cattle.io/creator: norman
  name: minio
  namespace: p-5crxt-pipeline
  resourceVersion: "1220817"
  selfLink: /apis/apps/v1/namespaces/p-5crxt-pipeline/deployments/minio
  uid: 790750c9-1b3c-4db1-bc02-dc38317d7034
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: minio
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: minio
      name: minio
    spec:
      containers:
      - args:
        - server
        - /data
        env:
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: admin-token
              name: pipeline-secret
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: admin-user
              name: pipeline-secret
        image: rancher/minio-minio:RELEASE.2019-09-25T18-25-51Z
        imagePullPolicy: Always
        name: minio
        ports:
        - containerPort: 9000
          name: minio
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 200M
          requests:
            cpu: 100m
            memory: 100M
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-03-25T14:50:19Z"
    lastUpdateTime: "2020-03-25T14:50:19Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-03-25T14:50:10Z"
    lastUpdateTime: "2020-03-25T14:50:19Z"
    message: ReplicaSet "minio-6964cfc479" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
