---
apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2020-03-25T14:50:10Z"
    labels:
      cattle.io/creator: norman
    name: docker-registry
    namespace: p-5crxt-pipeline
    resourceVersion: "1220739"
    selfLink: /api/v1/namespaces/p-5crxt-pipeline/services/docker-registry
    uid: 30689725-2d7c-4c0d-9007-68cbfd40807e
  spec:
    clusterIP: 10.43.8.82
    ports:
    - name: docker-registry
      port: 443
      protocol: TCP
      targetPort: 443
    selector:
      app: docker-registry
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2020-03-25T14:50:10Z"
    labels:
      cattle.io/creator: norman
    name: jenkins
    namespace: p-5crxt-pipeline
    resourceVersion: "1220734"
    selfLink: /api/v1/namespaces/p-5crxt-pipeline/services/jenkins
    uid: 5010fcad-9a5f-42f6-8378-b2bfd05d4ca1
  spec:
    clusterIP: 10.43.138.176
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: agent
      port: 50000
      protocol: TCP
      targetPort: 50000
    selector:
      app: jenkins
      jenkins: master
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2020-03-25T14:50:10Z"
    labels:
      cattle.io/creator: norman
    name: minio
    namespace: p-5crxt-pipeline
    resourceVersion: "1220755"
    selfLink: /api/v1/namespaces/p-5crxt-pipeline/services/minio
    uid: f0b3caaa-6ac8-426e-8d53-6212c6b964a5
  spec:
    clusterIP: 10.43.44.107
    ports:
    - name: minio
      port: 9000
      protocol: TCP
      targetPort: 9000
    selector:
      app: minio
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2020-03-25T14:50:10Z"
    generation: 1
    labels:
      cattle.io/creator: norman
    name: docker-registry
    namespace: p-5crxt-pipeline
    resourceVersion: "1220834"
    selfLink: /apis/apps/v1/namespaces/p-5crxt-pipeline/deployments/docker-registry
    uid: 08d165ba-a1e4-4a4d-9e75-f89c28b9bfe0
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: docker-registry
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: docker-registry
        name: docker-registry
      spec:
        containers:
        - env:
          - name: REGISTRY_HTTP_ADDR
            value: 0.0.0.0:443
          - name: REGISTRY_HTTP_TLS_CERTIFICATE
            value: /opt/crt/client.cert
          - name: REGISTRY_HTTP_TLS_KEY
            value: /opt/crt/client.key
          - name: REGISTRY_AUTH
            value: htpasswd
          - name: REGISTRY_AUTH_HTPASSWD_REALM
            value: Registry Realm
          - name: REGISTRY_AUTH_HTPASSWD_PATH
            value: /opt/auth/registry-token
          image: registry:2
          imagePullPolicy: Always
          name: docker-registry
          ports:
          - containerPort: 443
            name: docker-registry
            protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 200M
            requests:
              cpu: 100m
              memory: 100M
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /opt/crt/
            name: crt
            readOnly: true
          - mountPath: /opt/auth/
            name: auth
            readOnly: true
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: crt
          secret:
            defaultMode: 420
            secretName: registry-crt
        - name: auth
          secret:
            defaultMode: 420
            items:
            - key: registry-token
              path: registry-token
            secretName: pipeline-secret
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2020-03-25T14:50:22Z"
      lastUpdateTime: "2020-03-25T14:50:22Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2020-03-25T14:50:10Z"
      lastUpdateTime: "2020-03-25T14:50:22Z"
      message: ReplicaSet "docker-registry-68d44b9d47" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2020-03-25T14:50:10Z"
    generation: 1
    labels:
      cattle.io/creator: norman
    name: jenkins
    namespace: p-5crxt-pipeline
    resourceVersion: "1221001"
    selfLink: /apis/apps/v1/namespaces/p-5crxt-pipeline/deployments/jenkins
    uid: 6cef5076-9e3d-45b7-ab85-7e010e1d49ef
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: jenkins
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: jenkins
          jenkins: master
        name: jenkins
      spec:
        containers:
        - env:
          - name: ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                key: admin-token
                name: pipeline-secret
          - name: ADMIN_USER
            valueFrom:
              secretKeyRef:
                key: admin-user
                name: pipeline-secret
          - name: JAVA_OPTS
            value: -Xmx300m -Dhudson.slaves.NodeProvisioner.initialDelay=0 -Dhudson.slaves.NodeProvisioner.MARGIN=50
              -Dhudson.slaves.NodeProvisioner.MARGIN0=0.85 -Dhudson.model.LoadStatistics.clock=2000
              -Dhudson.slaves.NodeProvisioner.recurrencePeriod=2000 -Dhudson.model.UpdateCenter.never=true
          - name: NAMESPACE
            value: p-5crxt-pipeline
          - name: JENKINS_POD_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          image: rancher/pipeline-jenkins-server:v0.1.4
          imagePullPolicy: IfNotPresent
          name: jenkins
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 50000
            name: agent
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /login
              port: 8080
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: "1"
              memory: 1000000Ki
            requests:
              cpu: 500m
              memory: 300M
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: jenkins
        serviceAccountName: jenkins
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2020-03-25T14:51:33Z"
      lastUpdateTime: "2020-03-25T14:51:33Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2020-03-25T14:50:10Z"
      lastUpdateTime: "2020-03-25T14:51:33Z"
      message: ReplicaSet "jenkins-7bbb75bf66" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2020-03-25T14:50:10Z"
    generation: 1
    labels:
      cattle.io/creator: norman
    name: minio
    namespace: p-5crxt-pipeline
    resourceVersion: "1220817"
    selfLink: /apis/apps/v1/namespaces/p-5crxt-pipeline/deployments/minio
    uid: 790750c9-1b3c-4db1-bc02-dc38317d7034
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: minio
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: minio
        name: minio
      spec:
        containers:
        - args:
          - server
          - /data
          env:
          - name: MINIO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                key: admin-token
                name: pipeline-secret
          - name: MINIO_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                key: admin-user
                name: pipeline-secret
          image: rancher/minio-minio:RELEASE.2019-09-25T18-25-51Z
          imagePullPolicy: Always
          name: minio
          ports:
          - containerPort: 9000
            name: minio
            protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 200M
            requests:
              cpu: 100m
              memory: 100M
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2020-03-25T14:50:19Z"
      lastUpdateTime: "2020-03-25T14:50:19Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2020-03-25T14:50:10Z"
      lastUpdateTime: "2020-03-25T14:50:19Z"
      message: ReplicaSet "minio-6964cfc479" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
kind: List
