apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      service: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: registry.example.com/hatake_t14/php/apache:latest
#        env:
#        - name: LC_CTYPE
#          value: ja_JP.utf8
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 10080
          initialDelaySeconds: 5
          periodSeconds: 5
        command:
        - sh
        - "-c"
        - |
          ln -s /mnt/src/example1.co.jp /home/example1.co.jp && \
          ln -s /mnt/src/example2.co.jp /home/example2.co.jp && \
          ln -s /mnt/src/laravel-project /home/laravel-project && \
          ln -s /mnt/src/nuxtapp /home/nuxtapp && \
          apachectl -D FOREGROUND
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        volumeMounts:
        - name: disk
          mountPath: "/mnt/src"
        securityContext:
          privileged: true
      volumes:
      - name: disk
        persistentVolumeClaim:
          claimName: php-src-sample-pvc
