apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: php5-fpm
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: php5-fpm
    spec:
      containers:
      - name: php5-fpm
        image: php5-gke-php:latest
#        env:
#        - name: LC_CTYPE
#          value: ja_JP.utf8
        command:
          - sh
          - "-c"
          - |
            /usr/local/bin/dns-regist.sh && \
            /etc/init.d/blackfire-agent restart && \
            php-fpm
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: disk
          mountPath: "/mnt/src"
        securityContext:
          privileged: true
      volumes:
      - name: disk
        persistentVolumeClaim:
          claimName: php-src-sample-pvc
